[WIP] feat: add mustache and string-template for flow to compare them
tanohzana/reacli pull request #25
Opened 2019-02-15 22:59 UTC by tanohzana

# Issue #17 

**Summary:**

We used to parse files and use regexes to replace content inside files, but it was suggested that we delegate the job to some other package of which it's the job to do just that.

Here, as a WIP PR, I installed `mustache` and `string-template` and I tested both of them on the `flow option`.

What I noticed is that in order to escape `mustache`'s string, 3 brackets should be used, whereas `string-template` only uses 1.

However, `string-template` was last published to NPM 3 years ago, whereas `mustache`'s last publish was about 3 months ago.

**Changes:**

* Install `mustache` and `string-template`
* Change the way files are parsed in `reacli.js`

**Dependencies:**

No dependency

2019-02-15 23:07 UTC, gdarchen commented
Even if `mustache` requires 3 brackets, I would recommend to use it since it seems to be the most downloaded and maintained for the same features as `string-template`. From my point of view, having to write 3 brackets isn't a drawback that is big enough to make us choose to use `string-template`, when thinking of every advantages that could bring the big community of `mustache` users for future usages we could require.

2019-02-16 11:21 UTC, leocornillon commented
I totally agree with @gdarchen, there is much more projects dependent on `mustache` than `string-template`. Plus having a dependency called `mustache.js` is pretty cool :stuck_out_tongue:

2019-02-16 11:21 UTC, lcor-io requested changes
Let's go for `Mustache` ?

2019-02-16 11:22 UTC, tanohzana commented
Agreed then 😉

2019-02-16 20:12 UTC, tanohzana commented
Ready to be verified !

2019-02-18 13:58 UTC, gdarchen commented
It sounds now perfect to me. I merge it and publish it.

2019-02-18 13:58 UTC, merged